# Generated by Django 4.2.13 on 2025-11-06 07:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_tokens', models.IntegerField(default=256, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(2048)])),
                ('top_p', models.FloatField(default=0.9, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('top_k', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('default_jurisdiction', models.CharField(blank=True, max_length=100)),
                ('default_year_from', models.IntegerField(blank=True, null=True)),
                ('default_year_to', models.IntegerField(blank=True, null=True)),
                ('default_keywords_include', models.JSONField(blank=True, default=list)),
                ('default_keywords_exclude', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='OrgProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdictions', models.JSONField(blank=True, default=list)),
                ('clause_set', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'org_profile',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(choices=[('contract', 'Contract'), ('case', 'Case Law'), ('regulation', 'Regulation'), ('statute', 'Statute'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('jurisdiction', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('path', models.CharField(max_length=1000)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord', models.IntegerField()),
                ('heading', models.CharField(blank=True, max_length=500)),
                ('text', models.TextField()),
                ('embedding_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.document')),
            ],
            options={
                'db_table': 'chunks',
                'ordering': ['document', 'ord'],
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('A', 'Summarizer'), ('B', 'Clause Classifier'), ('C', 'Case-Law IRAC')], max_length=1)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('filters_used', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('register', 'User Registration'), ('upload', 'Document Upload'), ('ingest', 'Document Ingest'), ('chat', 'Chat Request'), ('export', 'Data Export'), ('settings_change', 'Settings Change')], max_length=50)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'doctype'], name='documents_user_id_4ea50e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['jurisdiction', '-date'], name='documents_jurisdi_f18d72_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['sha256'], name='documents_sha256_88e6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['document', 'ord'], name='chunks_documen_439d4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together={('document', 'ord')},
        ),
        migrations.AddIndex(
            model_name='chatlog',
            index=models.Index(fields=['user', '-created_at'], name='chat_log_user_id_55cf2c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatlog',
            index=models.Index(fields=['mode', '-created_at'], name='chat_log_mode_ac590b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='audit_user_id_78851c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='audit_action_30aa32_idx'),
        ),
    ]
