# Generated by Django 4.2.13 on 2025-11-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Associated document for modes A/B', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_logs', to='api.document'),
        ),
    ]
